### ISSUE TITLE
rabbitmq service confiqure in ingress controller

### ISSUE THREAD

**Issue by vijayrajan23** [dodo-foundation/discussions#2]
rabbitmq amqp configuration in nginx ingress

**Comment by FourTimes** [comment]
@vijayrajan23 Share me the ingress file

**Comment by vijayrajan23** [comment]
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/default-backend: ingress-nginx-controller
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Access-Control-Allow-Methods "POST, GET, OPTIONS";
      add_header Access-Control-Allow-Credentials true;
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
  name: test-ingress
spec:
  ingressClassName: nginx 
  rules:

    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-service
                port:
                  number: 80
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: react-service
                port:
                  number: 80
          - path: /home
            pathType: Prefix
            backend:
              service:
                name: react-service
                port:
                  number: 80
         
          - path: /rmq-ui/(.*)
            pathType: Prefix
            backend:
              service:
                name: rabbitmq-cluster
                port:
                  number: 15672

**Comment by FourTimes** [comment]
#vijayrajan could you please share your expectations with examples

**Comment by FourTimes** [comment]
@vijayrajan23 Please try this

```yml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbit-manage-ingress
  namespace: rabbitmq-system
  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: www.domainname.com
    http:
      paths:
      - path: /                                 # /rmq-ui/(.*)
        pathType: Prefix
        backend:
          service:
            name: rabbitmq-cluster
            port:
              number: 15672
```
